# Generated by Django 3.2.5 on 2021-08-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_group',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_group',
            field=models.ManyToManyField(to='core.Group'),
        ),
    ]
