# Generated by Django 3.2.5 on 2021-08-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210816_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='board',
        ),
        migrations.AddField(
            model_name='ticket',
            name='board',
            field=models.ManyToManyField(to='core.Board'),
        ),
    ]
