# Generated by Django 3.2.3 on 2021-09-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_priority_priority_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='board',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='priority',
            name='board',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.board'),
            preserve_default=False,
        ),
    ]
