# Generated by Django 3.2.7 on 2021-09-26 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_board_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_supervisors',
            field=models.ManyToManyField(related_name='ticket_supervisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_user',
            field=models.ManyToManyField(related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
