# Generated by Django 3.2.5 on 2021-10-04 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_board_semi_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='semi_supervisor',
        ),
        migrations.CreateModel(
            name='BoardSuperuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_ticket', models.BooleanField()),
                ('can_complete_ticket', models.BooleanField()),
                ('users', models.ManyToManyField(blank=True, related_name='board_superusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='superuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.boardsuperuser'),
        ),
    ]
