# Generated by Django 3.2.5 on 2021-10-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211004_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='superuser',
        ),
        migrations.AddField(
            model_name='boardsuperuser',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.board'),
        ),
    ]
