# Generated by Django 3.2.7 on 2021-10-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_boardsuperuser_can_create_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardsuperuser',
            name='can_create_tickets',
        ),
    ]
