# Generated by Django 3.2.7 on 2021-10-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_boardsuperuser_can_create_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardsuperuser',
            old_name='can_create_tickets',
            new_name='can_create_ticket',
        ),
    ]
