-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIGMgRIc285FRK/Av+/kB036GCHKmwJmRKswwX4BC9nEyoAoGCCqGSM49
AwEHoUQDQgAEsdGCOpxE5ggTtFFSuGoRcWFljgWgrjyvVjq9Iva7TkXjuLlKPLzu
m10IcM386kCXiy5YmnCC7WiKnmkzsfwPgw==
-----END EC PRIVATE KEY-----
